import React, {useState, useEffect } from 'react';
import { useSession } from "next-auth/react";
import openSocket from "socket.io-client";
import Header from '../components/Header/Header';
import Head from 'next/head';
// import GoogleButton from '../component/GoogleButton/GoogleButton';

type Token = {
    symbol: string,
    rate: string,
    time: number
}
type Message = {
    title: string
    type: string,
    block: string,
    token: Token[],
};

const Home = ()=> {

    const { data: session } = useSession();
    const socket  = openSocket('http://localhost:8000');
    const [title, setTitle] = useState('DISCONNECTED');
    const [block, setBlock] = useState('0');

    const dataMessage = {
            title,
            type: '',
            block: '0',
            token: [{
                symbol: 'NO',
                rate: '10',
                time: 11110
            }]
    };

    const [messageState, setMessage] = useState( dataMessage );

    useEffect(() => {
        socket.on('connect', () => {
            setTitle('CONNECTED');
             socket.emit('subscribe', {
                 type: 'subscribe',
                 event: 'new subscribe',
             });
        });
    }, []);


    // useEffect(()=>{
    //     socket.on('message', (message)=> {
    //         console.log('message', message.data.token);
    //         setBlock(message.block);
    //         setMessage(message.data);
    //     });
    //
    // }, [messageState.block] );


    function ListItem(props) {
        return <li>{props.message.symbol}: {props.message.rate}</li>;
    }

    return (
        <>
        {/*<Head>*/}
        {/*    <title>Create Next App</title>*/}
        {/*    <meta name='description' content='Generated by create next app' />*/}
        {/*    <meta name='viewport' content='width=device-width, initial-scale=1' />*/}
        {/*    <link rel='icon' href='/favicon.ico' />*/}
        {/*</Head>        {/*<Head>*/}
        {/*    <title>Create Next App</title>*/}
        {/*    <meta name='description' content='Generated by create next app' />*/}
        {/*    <meta name='viewport' content='width=device-width, initial-scale=1' />*/}
        {/*    <link rel='icon' href='/favicon.ico' />*/}
        {/*</Head>*/}
        <main className='bg-gray-100 min-h-screen'>
        {/*<nav >*/}
        {/*    <div>*/}
        {/*        {session && session.user ? (*/}
        {/*            <button onClick={() => signOut()}>Sign out</button>*/}
        {/*        ) : (*/}
        {/*            <button onClick={() => signIn()}>Sign in</button>*/}
        {/*        )}*/}
        {/*    </div>*/}
        {/*</nav>*/}

        {/*<Htag tag ='h3'>{title}</Htag>*/}
        {/*<Htag tag ='h6'>CURRENT BLOCK: {block}</Htag>*/}
        {/*    <div className="col-md-6 offset-md-3 col-sm-12">*/}
        {/*        <ul>*/}
        {/*            {*/}
        {/*                messageState.token.map((token) => <ListItem key={token.symbol} message={token}/>)*/}
        {/*             }*/}
        {/*        </ul>*/}
        {/*    </div>*/}

        {/*<Button appearance='primary'>Login</Button>*/}
        {/*<Button appearance='ghost'>Help</Button>*/}
        </main>
        </>
  );

};

export default Home;